/**
 * fixtures-audit.spec.ts
 *
 * Structural validation of fixture/seed files for all three sections of the
 * CNCF Landscape. These are file-system tests (no browser required) that
 * catch broken seed data before E2E runs begin.
 *
 * SO-54: People data files added to the audit matrix (GH #15, gap G6).
 *        Two locations:
 *          - tests/fixtures/people/ — timeline feed seed (changelog-seed.json)
 *          - src/data/people/       — generated by Go backend (leadership, emeritus, etc.)
 */
import { test, expect } from '@playwright/test';
import { existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = dirname(__filename);

// ─── Projects & Members fixtures (tests/fixtures/<subdir>/) ───────────────────

const SITE_TO_SUBDIR: Record<string, string> = {
  projects: 'projects',
  endusers: 'members',
};

const FIXTURE_REQUIREMENTS = [
  { site: 'projects', file: 'projects-seed.json',   minItems: 3 },
  { site: 'projects', file: 'changelog-seed.json',  minItems: 1 },
  { site: 'endusers', file: 'members-seed.json',    minItems: 3 },
  { site: 'endusers', file: 'architectures-seed.json', minItems: 1 },
];

for (const req of FIXTURE_REQUIREMENTS) {
  test(`${req.site}/fixtures/${req.file} exists and has >= ${req.minItems} items`, async () => {
    const subdir = SITE_TO_SUBDIR[req.site];
    const path   = join(__dirname, '../../tests/fixtures', subdir, req.file);
    expect(existsSync(path)).toBe(true);
    const data = JSON.parse(readFileSync(path, 'utf-8'));
    expect(Array.isArray(data)).toBe(true);
    expect(data.length).toBeGreaterThanOrEqual(req.minItems);
  });
}

test('fixture files contain no PII (email addresses)', async () => {
  const piiPattern = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/;
  for (const req of FIXTURE_REQUIREMENTS) {
    const subdir = SITE_TO_SUBDIR[req.site];
    const path   = join(__dirname, '../../tests/fixtures', subdir, req.file);
    if (existsSync(path)) {
      const content = readFileSync(path, 'utf-8');
      expect(content).not.toMatch(piiPattern);
    }
  }
});

// ─── People timeline-feed fixtures (tests/fixtures/people/) ───────────────────
//
// People changelog-seed.json mirrors the format of projects/changelog-seed.json
// but uses Person objects (handle, name, github) rather than Project objects.

test('people/fixtures/changelog-seed.json exists and has >= 1 item', async () => {
  const path = join(__dirname, '../../tests/fixtures/people/changelog-seed.json');
  expect(existsSync(path)).toBe(true);
  const data = JSON.parse(readFileSync(path, 'utf-8')) as Array<Record<string, unknown>>;
  expect(Array.isArray(data)).toBe(true);
  expect(data.length).toBeGreaterThanOrEqual(1);
});

test('people/fixtures/changelog-seed.json entries have required fields (id, type, timestamp, person)', async () => {
  const path = join(__dirname, '../../tests/fixtures/people/changelog-seed.json');
  expect(existsSync(path)).toBe(true);
  const data = JSON.parse(readFileSync(path, 'utf-8')) as Array<Record<string, unknown>>;
  const REQUIRED_ENTRY_FIELDS = ['id', 'type', 'timestamp', 'person'];
  const REQUIRED_PERSON_FIELDS = ['handle', 'name', 'github'];
  for (const entry of data) {
    for (const field of REQUIRED_ENTRY_FIELDS) {
      expect(entry[field]).toBeTruthy();
    }
    const person = entry['person'] as Record<string, unknown>;
    for (const field of REQUIRED_PERSON_FIELDS) {
      expect(person[field]).toBeTruthy();
    }
  }
});

test('people/fixtures/changelog-seed.json contains no PII (email addresses)', async () => {
  const piiPattern = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/;
  const path = join(__dirname, '../../tests/fixtures/people/changelog-seed.json');
  if (existsSync(path)) {
    const content = readFileSync(path, 'utf-8');
    expect(content).not.toMatch(piiPattern);
  }
});

// ─── People data files (src/data/people/) ─────────────────────────────────────
//
// People data is generated by the Go backend (not hand-crafted fixtures), so
// we validate the files that are always present (committed to the repo) and
// skip files that are generated only during the build (maintainers.json,
// heroes.json) with a soft check.

const REPO_ROOT = join(__dirname, '../..');

const PEOPLE_DATA_REQUIREMENTS = [
  { file: 'src/data/people/people-emeritus.json', minItems: 3,  required: true },
  { file: 'src/data/people/leadership.json',      minItems: 1,  required: true },
  { file: 'src/data/people/leadership-roles.json', minItems: 1, required: true },
  { file: 'src/data/people/memorial.json',        minItems: 0,  required: true },
  { file: 'src/data/people/staff-support.json',   minItems: 0,  required: true },
  // Go-generated files — present after build but not always committed
  { file: 'src/data/people/maintainers.json',     minItems: 1,  required: false },
  { file: 'src/data/people/heroes.json',           minItems: 0,  required: false },
];

for (const req of PEOPLE_DATA_REQUIREMENTS) {
  test(`people: ${req.file} ${req.required ? 'exists' : 'is valid when present'} and is valid JSON${req.minItems > 0 ? ` with >= ${req.minItems} items` : ''}`, async () => {
    const path = join(REPO_ROOT, req.file);

    if (!req.required && !existsSync(path)) {
      // Build-generated file not present yet — skip gracefully
      console.log(`Skipping ${req.file} (not yet generated)`);
      return;
    }

    expect(existsSync(path)).toBe(true);

    const raw  = readFileSync(path, 'utf-8');
    let data: unknown;
    expect(() => { data = JSON.parse(raw); }).not.toThrow();

    if (req.minItems > 0) {
      expect(Array.isArray(data)).toBe(true);
      expect((data as unknown[]).length).toBeGreaterThanOrEqual(req.minItems);
    }
  });
}

test('people: emeritus data contains required fields (handle, name, category)', async () => {
  const path = join(REPO_ROOT, 'src/data/people/people-emeritus.json');
  expect(existsSync(path)).toBe(true);
  const data = JSON.parse(readFileSync(path, 'utf-8')) as Array<Record<string, unknown>>;
  expect(Array.isArray(data)).toBe(true);
  const REQUIRED_FIELDS = ['handle', 'name', 'category'];
  for (const item of data.slice(0, 10)) {
    for (const field of REQUIRED_FIELDS) {
      expect(item[field]).toBeTruthy();
    }
  }
});

test('people: leadership data contains required fields (handle, name, title)', async () => {
  const path = join(REPO_ROOT, 'src/data/people/leadership.json');
  expect(existsSync(path)).toBe(true);
  const data = JSON.parse(readFileSync(path, 'utf-8')) as Array<Record<string, unknown>>;
  expect(Array.isArray(data)).toBe(true);
  const REQUIRED_FIELDS = ['handle', 'name', 'title'];
  for (const item of data) {
    for (const field of REQUIRED_FIELDS) {
      expect(item[field]).toBeTruthy();
    }
  }
});

test('people: data files contain no PII (email addresses)', async () => {
  const piiPattern = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/;
  const filesToCheck = [
    'src/data/people/people-emeritus.json',
    'src/data/people/leadership.json',
    'src/data/people/memorial.json',
  ];
  for (const file of filesToCheck) {
    const path = join(REPO_ROOT, file);
    if (existsSync(path)) {
      const content = readFileSync(path, 'utf-8');
      expect(content).not.toMatch(piiPattern);
    }
  }
});
